version: '3.8'
services:
  react-app:
    container_name: react
    build: .
    image: juansebastiangb/reactapp
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
    environment:
      - REACT_APP_NAME=MASTER
      - CHOKIDAR_USEPOLLING=true